name: Upload users.json & avatars to Google Cloud Storage

on:
  push:
    branches: [main]
    paths:
      - users.json
      - avatars/**
  workflow_dispatch:

jobs:
  upload-to-gcs:
    name: Upload to Google Cloud Storage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ksug-ai

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload users.json to GCS
        run: |
          echo "Uploading users.json..."
          gsutil cp users.json gs://ksug-ai-bucket1/awstronaut/users.json

      - name: Upload avatars to GCS
        run: |
          echo "Uploading avatars..."
          gsutil -m cp -r avatars/* gs://ksug-ai-bucket1/awstronaut/avatars/
