name: Purge jsDelivr CDN after merge

on:
  push:
    branches:
      - main
    paths:
      - 'users.json'

jobs:
  purge-cdn:
    runs-on: ubuntu-latest

    steps:
      - name: Purge jsDelivr cache for users.json
        run: |
          echo "Triggering jsDelivr purge..."
          curl -s -X GET "https://purge.jsdelivr.net/gh/k8sug/awstronaut@main/users.json"
